name: Build on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build_web_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-verson: '17'

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        uses: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/
